version: '3.7'

services:
  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - validation-db:/var/lib/postgresql/data

volumes:
  validation-db: